### ISSUE TITLE
On initial setup, error: cannot open config_db.php

### ISSUE THREAD

**Issue by teewuane** [devinemke/submgr#10]
To get this I installed the files on my server then went to the root of the directory in a web browser. It asked me for the mysql host, username, password. I click continue then enter in the database name. Once I click submit I get the error `cannot open config_db.php`.

It looks like it is relying on config_db.php but that file doesn't appear to exist in the repository.

**Comment by teewuane** [comment]
After looking into this for a minute, it looks like php is not able to write to the folder. I'll figure this out.

**Comment by devinemke** [comment]
@teewuane As I gather you have figured out: whatever user PHP is running as (Apache?) needs full read/write access to the directory on your web server where SM is installed.

Additionally: the directory you specify in your **_upload_path_** settings also needs full read/write by the PHP user (this is where SM stores the uploaded submission files). The **_upload_path_** should be completely outside of your server's public doc root.

Hope this helps.
