### ISSUE TITLE
Getting "mail failure" when submitting a submission.

### ISSUE THREAD

**Issue by teewuane** [devinemke/submgr#11]
Everything else seems to be working properly.. the file uploads and I can download it from the submissions page.

I'm guessing the mail failure has to do with my SMTP settings. They should be correct and my email server definitely allows SMTP. Is there a way to get more of the error from the `$mail->Send()`?

**Comment by teewuane** [comment]
I see that I have a wrong password from my client, but it would still be nice to get some of the error printed out with the "mail failure" to make it easier to track down :)

**Comment by devinemke** [comment]
@teewuane Have you explicitly set your SMTP connection credentials in these SM config settings:

```
mail_method = SMTP
smtp_secure = SSL? TLS?
smtp_port = 465? 587?
smtp_auth = probably yes
smtp_host = ???
smtp_username = ???
smtp_password = ???
```
> Is there a way to get more of the error from the `$mail->Send()`?

Yes, when logged is as an admin go to **/Maintenance/Test Mail/**. There you can see verbose output from your current mail configuration (and test others without messing up your current config).

**Comment by teewuane** [comment]
Yes, I've set my SMTP settings in the config. I believe I have a bad password as I'm not able to login to the webmail website with the same username and password which *should* work.

That 'test mail' function in maintenance is super useful! Thank you!
