### ISSUE TITLE
request: Do not rename file names to match the submission id

### ISSUE THREAD

**Issue by teewuane** [devinemke/submgr#12]
I'm looking at the `upload` function in inc_common.php and trying to figure out where the file is renamed to match the submission id number.

Instead of this...

`my-short-story.pdf` is renamed to `15.pdf`

I'd like something similar to this...

`my-short-story.pdf` is renamed to `my-short-story--15.pdf`

Something that will ensure a unique name and has a tie to the submission id while keeping the original file name. I think it's okay to strip out weird characters and slashes and urldecode the name.

Does the rest of the code rely on the uploaded file having a name that matches the id of a submission?

Same question and request for files uploaded for actions as well.

Thank you!

**Comment by devinemke** [comment]
> Does the rest of the code rely on the uploaded file having a name that matches the id of a submission?

The short answer is: yes, the code does rely on this.

The **submissions** table stores the **title** of the submission, and the file **extension**, but **_not_** the original file name (which can often be **MyGreatStory_FINAL_FINAL_VERSION6.6.6.pdf** or some such, that does not even include the submission title). This was an early design decision of SM: there is no need to retain the original file name, rather just use the primary key value (**_submission_id_** + **_ext_**). It would require a lot of work to alter not only the code that programmatically serves up the submission files, but also the underlying data schema that stores them.

> Same question and request for files uploaded for actions as well.

Same answer: the **actions** table likewise stores the file **extension**.
The convention here is that submission files are all named **_submission_id.ext_**
and action files are all named **_action_action_id.ext_**.

These are all stored in the **_upload_path_** (organized by year).

Hope this makes sense.

**Comment by teewuane** [comment]
@devinemke Makes sense, thanks!
