### ISSUE TITLE
ErrorException Warning: foreach() argument must be of type array|object, null given

### ISSUE THREAD

**Issue by teewuane** [devinemke/submgr#15]
Hi, here is a warning I'm getting.

It is coming from `inc_common.php` line `2211`.

```
foreach ($payment_vars['out'] as $value)
```

Looks like $payment_vars is null?

This also happens on a different line in the same file, line `2218`...

```
foreach ($payment_vars['in'] as $value)
```

The error I get here is similar but different...

```
ErrorException
Warning: Trying to access array offset on value of type null
```

I hope this helps!

I recognize these are all just warnings but figured I'd still report them!
Thanks!

**Comment by devinemke** [comment]
@teewuane Do you have your SM configured to accept payments? That is: is the table in **/config/payment variables/** populated? and is a **redirect_url** set? either in one of your active genres, or globally (in **/config/general configuration/**)? Only then will the `$payment_vars` array exist (created by the **get_payment_vars()** function).

Perhaps this again is additional error handling from **sentry.io** ???
Please let me know. thanks. -DE

**Comment by teewuane** [comment]
It took us a bit to get the proper variables set for authorize.net, it's possible that when we were testing, before we had it properly configured, that this is when this errors occurred.

It doesn't seem to be reporting this error anymore since we do have the payment gateway properly configured.

**Comment by devinemke** [comment]
@teewuane Glad you got this sorted.

fwiw: on my local dev **_*AMP_** environment (like many devs I suspect) I have PHP configured with `error_reporting = E_ALL` to show all errors (including ones that would typically be suppressed on a live production server). I have never seen the error in question here regarding `$payment_vars` (with or without the SM payment system enabled). Again, I have not used **sentry.io** but I cannot see why that would be throwing errors beyond what would be visible from PHP in `E_ALL` mode.

Anyway, please close this issue if all good. Thanks. -DE
