### ISSUE TITLE
Unauthenticated CSRF problems

### ISSUE THREAD

**Issue by jayyx2** [devinemke/submgr#3]
### Problem
When attempting a first-time submission, some users are reporting CSRF errors. Some users are consistently hitting this to the point they are unable to submit. The HAR file from one of these users seems to show a condition where the tokens do not match upon hitting submit.

### Reproduction Steps
- Intermittent for most users, random occurrences
- Some users follow the normal submission process and get hit with CSRF error before getting to the "Confirm" submission page

### Notes
- The site itself is running on https://www.domain.com, but when running submission manager, it's using https://domain.com.
- Some modifications have been made to the code, but, mostly CSS/style. The other modification was removing required address-related fields

### Investigation
- There seems to be multiple variables related to the CSRF form_hash. I believe the user is hitting this conditional statement in inc.common:
```
	if ($arg == 'validate')
	{
		// if (!isset($_POST['form_hash']) || (isset($_POST['form_hash']) && isset($_SESSION['form_hash']) && $_POST['form_hash'] != $_SESSION['form_hash'])) {kill_session('regenerate'); $_SESSION['form_hash'] = $GLOBALS['nonce']; exit_error('form_hash');} else {$_SESSION['form_hash'] = $GLOBALS['nonce'];}
		if (!isset($_POST['form_hash']) || !isset($_SESSION['csrf_token']) || (isset($_POST['form_hash']) && isset($_SESSION['csrf_token']) && $_POST['form_hash'] != $_SESSION['csrf_token'])) {
			kill_session('regenerate');
			exit_error('csrf_token');
		} else {
			$GLOBALS['form_hash'] = $_SESSION['csrf_token'];
		}
```
inc.common runs $GLOBALS['nonce'] = get_token();

```
function get_token()
{
	if (version_compare(PHP_VERSION, '7.0.0', '>='))
	{
		$token = bin2hex(random_bytes(20));
	}
	elseif (extension_loaded('openssl'))
	{
		$token = bin2hex(openssl_random_pseudo_bytes(20));
	}
	else
	{
		$token = sha1(uniqid(mt_rand(), true) . session_id());
	}

	return $token;
}
```

The token is later used by form_hash() function
```
function form_hash($arg)
{
	if ($arg == 'session')
	{
		// $_SESSION['form_hash'] = $GLOBALS['nonce'];
		if (isset($_SESSION['csrf_token'])) {
			$GLOBALS['form_hash'] = $_SESSION['csrf_token'];
		} else {
			$_SESSION['csrf_token'] = $GLOBALS['nonce'];
			$GLOBALS['form_hash'] = $_SESSION['csrf_token'];
		}
	}

	if ($arg == 'validate')
	{
		// if (!isset($_POST['form_hash']) || (isset($_POST['form_hash']) && isset($_SESSION['form_hash']) && $_POST['form_hash'] != $_SESSION['form_hash'])) {kill_session('regenerate'); $_SESSION['form_hash'] = $GLOBALS['nonce']; exit_error('form_hash');} else {$_SESSION['form_hash'] = $GLOBALS['nonce'];}
		if (!isset($_POST['form_hash']) || !isset($_SESSION['csrf_token']) || (isset($_POST['form_hash']) && isset($_SESSION['csrf_token']) && $_POST['form_hash'] != $_SESSION['csrf_token'])) {
			kill_session('regenerate');
			exit_error('csrf_token');
		} else {
			$GLOBALS['form_hash'] = $_SESSION['csrf_token'];
		}
	}
}
```

### Questions
- Is all the variable interchange necessary? For example can we instead do this?
 `<input type="hidden" id="form_hash_main" name="form_hash" value="' . $_SESSION['csrf_token'] . '">`

- Is it absolutely necessary to do pre-authentication CSRF on the first-time submitter form?

**Comment by devinemke** [comment]
> The site itself is running on https://www.domain.com/, but when running submission manager, it's using https://domain.com/.

Just make sure that the whatever is the canonical domain that you are using is reflected in your **app_url** setting in your SM config. I say that as there could be some session cookie propagation issues if using both domains.

> Some modifications have been made to the code, but, mostly CSS/style. The other modification was removing required address-related fields

Please be advised that SM has built-in mechanisms for custom PHP + CSS to override _some_ default functionality. You can create **custom.php** and **custom.css** files for this purpose. Please consider using these rather than direct mods of the code base (will make upgrading your SM much easier).

> There seems to be multiple variables related to the CSRF form_hash.

Yeah, at one time SM used **per page request** CSRF token regeneration rather than **per session**. This proved to have too many usability issues (browser _back_ button, multiple SMs open in different tabs, etc...). So there was some refactoring of the **form_hash()** function back in 2021 to change that. In fact you can still see the commented out code that was used for **per page request** CSRF token regeneration still sitting there.

> Is all the variable interchange necessary?

Again this may be some fallout from the **form_hash()** refactoring. Perhaps you are right and this can all be simplified.

> Is it absolutely necessary to do pre-authentication CSRF on the first-time submitter form?

While I agree that there is not much security benefit to that, I simply made the decision to add the CSRF token to the $_SESSION array since we are _always_ creating a new user session regardless of whether it is the first submission or a repeat submitter who has authenticated.

Let me look into this further, see if I can simplify, and get back to you. Open to any/all suggestions. Appreciate the feedback. Thanks.

-DE

**Comment by devinemke** [comment]
@jayyx2 ok as promised I have simplified the CSRF validation.

I was never able to repro the issue you describe, neither on my local dev machine, nor any of my live production platforms. You yourself mentioned that this was intermittent, and not sure of the exact set of circumstances causing the issue.

The 4 places where we were dealing with nonce/tokens are these:

1. **$GLOBALS['nonce']**
2. **$_SESSION['csrf_token']**
3. **$_POST['form_hash']**
4. **$GLOBALS['form_hash']**

**$GLOBALS['nonce']** is created on _every_ page request (via the **get_token()** function) and is used elsewhere around the code base for things that have nothing to do with CSRF validation (for example: nonce is passed to all `<script>` tags and used for password reset tokens).

The **form_hash()** function initially checks for the existence of **$_SESSION['csrf_token']** and if it does _not_ exist, sets it to **$GLOBALS['nonce']**. Then for validation **$_SESSION['csrf_token']** is compared to **$_POST['form_hash']** (the hidden form field that passes the token). If **$_POST['form_hash']** or **$_SESSION['csrf_token']** do _not_ exist, or they do not equal each other, then the validation fails.

The extra step of using **$GLOBALS['form_hash']** has been completely eliminated. As you sagely pointed out this variable interchange was not necessary.

Be advised: I cannot be 100% sure that this will address the issue you describe (as again I was unable to repo) but hopefully this simplification will help. Please let me know if you continue to see this issue. If you do, then we can further troubleshoot. I will leave this open for the time being.

btw: I do hope you were able to get **custom.php** and/or **custom.css** working in your live SM install for whatever modifications you need. Again, this is the cleaner/easier way of handling those type of mods.

Thanks -DE

**Comment by jayyx2** [comment]
Thanks so much for your help with this. I will follow-up once I am able to get one of the users experiencing the issue to test again.

I haven't implemented custom.css or custom.php yet, I will read the doc and follow-up if I have questions. Thanks again!

**Comment by jayyx2** [comment]
Sorry, are there any documents for custom.css or custom.php? I presume anything in custom.css overrides any other CSS -- but how does custom.php work? For example, I want to change which fields are required. Our publication only requires first name, last name, and email for contact details.

**Comment by devinemke** [comment]
> Sorry, are there any documents for custom.css or custom.php?

This is an undocumented feature (have to update the included [**documentation.html**](https://github.com/devinemke/submgr/blob/main/documentation.html)). Here's the deal:

**custom.css** : included at the bottom of [**css.php**](https://github.com/devinemke/submgr/blob/main/css.php). Use any valid CSS syntax to override what is specified above. You can and should use the SM config GUI for whatever possible (fonts, colors, logos, etc...) but you can use this for other things beyond what is in the GUI. This is all called within the existing `<style>` tags, so no need to include the in your custom file.

**custom.php** : included at the bottom of [**inc_common.php**](https://github.com/devinemke/submgr/blob/main/inc_common.php). Again, can overridden various PHP function/variables. For example to change which form fields are required you could tweak the **$fields** + **$required_fields** arrays. This then affects all upstream server-side + client-side form validation.

A simple example:

```
$fields['address1']['required'] = '';
unset($required_fields['address1']);
```

I have actually been thinking for a while on how best to add customization of form fields within the SM GUI. I was thinking of a list of fields with a simple checkbox next to each to specify requirement. It's a bit tricky as some of the fields are interrelated.

For example: if you choose _USA_ for the **country** field, then **state** and **zip** are required (not for other countries).
Similarly if you choose a submission genre that charges a fee then the payment/credit card fields become visible, and thus required.

I have to figure out the best way to implement this, both on the front end, as well as the back. Does this merit its own table in the database, with the field names and (at least) a boolean column for required/not required (maybe other columns, for size/maxlength)? Or perhaps this could all live in a row in the existing **config** table in some sort of delimited list or serialized array/object.

Again, open to ideas. Thanks. -DE

**Comment by jayyx2** [comment]
Thanks for the help with the sample. I was not able to get it to working completely without manually modifying inc_common.php a bit. It worked to specify which fields weren't required. I then ran into the problem you described in your example due to the country field being USA. In addition, I could not figure out how to remove the additional fields from the submission form since they are echoed to the page within a function.

I looked into modifying 'function form_check()' from custom.php to workaround the problem you described with USA for the country field, but found it's not possible to override an existing function name in PHP with the way the code is currently structured. Some of the functions which echo data to the final HTML output would need to be defined as variables. This **_could_** be a way to offer the customization of the form fields without much effort. I found a [sample here](https://stackoverflow.com/questions/8691884/how-to-unset-a-function-definition-just-like-we-unset-a-variable).

### Sample from stackoverflow.com

$upper = function($str) {
    return strtoupper($str);
};

echo $upper('test1');
// outputs: TEST1

unset($upper);

echo $upper('test2');
// Notice: Undefined variable: upper
// Fatal error: Function name must be a string

**Comment by devinemke** [comment]
@jayyx2 Ok let me look into this further and figure out the best way forward.

Just to be clear: you want to be able to make certain form fields not required, but also not on the form at all (invisible / disabled)? is this correct?

As discussed I think an entirely new configuration UI is going to be required here. And there is a lot of form display/validation logic that is going to have to be refactored.

I'll get back to you. Thanks. -DE

**Comment by jayyx2** [comment]
@devinemke : I upgraded to the latest version and some users are still getting the CSRF error on submit. I will add the other logs you suggest in email and try to have them test again.

We’re Sorry,

We are experiencing temporary difficulties completing your request at this time. Please try again later.
If your problem persists, please contact --

error: csrf_token

**Comment by devinemke** [comment]
@jayyx2 ok re-opening this.

Again, I cannot repro this at all, on any platform, so I am going to need some troubleshooting guidance.

Please do try those **var_dump()** suggestions that I sent you on **$_POST['form_hash']** + **$_SESSION['csrf_token']**.
Let me know what you find.

Thanks -DE

**Comment by jayyx2** [comment]
The user consistently reproducing this is no longer able to reproduce. I believe this can be closed. Thanks so much!
