### ISSUE TITLE
customizing form fields

### ISSUE THREAD

**Issue by devinemke** [devinemke/submgr#9]
@jayyx2 We are getting _way_ off topic in that original #3 CSRF thread, so i am starting this new one.

So based on the use case that you outlined in the other thread, I have totally refactored the **form_main()** function and all of its associated validation/display logic to allow for easy customizing of form fields. Before, there was a lot of old code that directly echoed HTML and drew lots of form logic from different places/variables. Now there is a unified **$fields** array that controls all of this logic. Here's how this works:

In your **custom.php** you can easily alter the properties of **$fields** to control what is required/displayed. For example: certain fields are required by default (as defined in **$fields**). If you wanted all of the address related fields to _not_ be required you could do this:
```
$fields['address1']['required'] = '';
$fields['address2]['required'] = '';
$fields['city']['required'] = '';
$fields['state']['required'] = '';
$fields['zip']['required'] = '';
$fields['country']['required'] = '';
```
All of those fields will still be enabled/visible, but will simply _not_ be required via the server-side/client-side form validation. Conversely, if there are fields that _are not_ required by default, you can make them required much the same way:
```
$fields['company']['required'] = 'Y';
$fields['address2']['required'] = 'Y';
```
If there are fields that you do not want on the form at all, then you can do something like this:
```
unset($fields['city']);
unset($fields['state']);
unset($fields['zip']);
unset($fields['country']);
```
Then you can also tweak the form labels. For example if you are using SM to collect applications or some such, you might want to make the **comments** field not only required (it is _not_ by default) but also called something else:
```
$fields['comments']['required'] = 'Y';
$fields['comments']['name'] = 'mission statement';
```
Under the hood, the **comments** field ID is the same, but this just changes what is displayed on the UI form label.

Hopefully this (combined with **custom.css**) will allow you do to whatever customization that you require without hacking core. Please let me know if this works for your SM install.

I have been testing this extensively with different combinations of mods to **$fields**, but there are now many different scenarios that I may have overlooked.

As discussed in the other thread: All of this seems like a stopgap solution until I can put together a full-fledged UI for form customization. That is, a whole new section in the SM admin config where you can make these kinds of tweaks. I was thinking this would be its own database table, the schema would match that of the **$fields** array, with the form ID as the primary key and the same properties as additional database columns. Then the UI would have checkboxes to toggle required/enabled and text boxes to adjust labels, maxlength, etc...

All this work done now goes a long way to making that process much easier going forward. In fact once that new table exits, it could be a very simple function called **get_fields()** or some such to simply create the exiting **$fields** array, and all of the existing logic _should_ still work the exact same way (without needing **custom.php** at all).

Always open to ideas/improvements.

Thanks -DE

**Comment by devinemke** [comment]
@jayyx2 So I have now completed the custom form fields GUI negating the need to use a **custom.php** for that purpose at all. In fact this new version is incompatible with **custom.php** as described above. The field properties now live in their own table and in the GUI you can tweak the **Labels**, **Default Values**, **Max Lengths**, and whether or not fields are **Enabled** and/or **Required**.

This UI replaces many of the directives that were stored in the **General** config table, as there is now some overlapping configurations (**max_file_size**, **max_comments_size**, **default_country**, **default_mailing_list**, **use_genres**).

This bumps the version number up to **3.41** and as such will require a **data structure update** (new table, removal of things from exiting tables). Admin users will be prompted to update structure upon initial login.

Please give this version a try, and hopefully this will allow you to do whatever modifications you need without hacking core. Let me know how it goes.

Thanks -DE

**Comment by jayyx2** [comment]
Amazing, thanks so much for your effort on this. I will try it soon and post notes here.

**Comment by jayyx2** [comment]
The form customization works perfectly thus far. Thanks so much!

I wonder if it is possible to add a configuration option in the same page for the placeholder value for each form field? In addition, it would be nice to be able to customize the class field on both the label and input.

For example, variables for the '**' spots:
```
<div class="container" style="max-width:600px;">
        <div class="mb-2">
            <label class="**form-label**" for="first_name" id="label_first_name">First name</label>
            <input type="text" class="**form-control form-control-sm**" id="first_name" name="first_name" placeholder="**First name**" value="'; if (isset($first_name)) {echo $first_name;} echo '" maxlength="50">
        </div>
</div>
```

**Comment by jayyx2** [comment]
The form customization works perfectly thus far. Thanks so much!

I wonder if it is possible to add a configuration option in the same page for the placeholder value for each form field? In addition, it would be nice to be able to customize the class field on both the label and input.

```
<div class="container" style="max-width:600px;">
        <div class="mb-2">
            <label class="**form-label**" for="first_name" id="label_first_name">First name</label>
            <input type="text" class="**form-control form-control-sm**" id="first_name" name="first_name" placeholder="**First name**" value="'; if (isset($first_name)) {echo $first_name;} echo '" maxlength="50">
        </div>
</div>
```

**Comment by devinemke** [comment]
@jayyx2 Ok I will have a look at this.

The CSS class part is a bit tricky as the form classes are already dynamic, that is, when the form is submitted, the JS validation checks which required fields are not filled out, and will change all labels/fields to the **error** class with red fonts/borders `#FF0000`.

**Comment by jayyx2** [comment]
I would suggest skipping that piece of it then, it would introduce potential problems w/ error handling + form validation. The placeholder value would certainly be nice to have in the new fields config area.

**Comment by devinemke** [comment]
@jayyx2 regarding your HTML **placeholder** idea:

I have not (yet) added placeholders (nor CSS classes) to the customizable **fields** table, but I have yet another stopgap/band-aid/kludge solution to your request.  As we already have **custom.php** and **custom.css** we now finally have (maybe you can guess where this is going): **custom.js**

As the name suggests, this is a custom file that is included() at the bottom of **javascript.php** (much the same way **custom.css** is added at the bottom of **css.php**) and allows you to add whatever additional custom JS that you wish (while inheriting all the stock JS variables/functions that are already there). And much like **custom.css** which is already nested in `<style>` tags, **custom.js** already nested in `<script>` tags (no need to add).

So...let's say you wanted to add placeholders to the main form. Create a **custom.js** that looks something like this:
```
document.addEventListener("DOMContentLoaded", function()
{
	if (document.getElementById("form_main"))
	{
		var custom_fields = {
		first_name: "Please type your First Name",
		last_name: "Please type your Last Name",
		email: "Please type your Email Address"
		};

		for (var key in custom_fields)
		{
			if (document.getElementById(key)) {document.getElementById(key).placeholder = custom_fields[key];}
		}
	}
});
```
I have tested this on all current major browsers, and it is working as expected.
As you can see there is a bunch of nested conditional logic here to check:

1. Is the entire DOM tree loaded? (we are referencing DOM IDs that do not yet exist)
2. Does the **form_main** ID exist? (it does _not_ exist on every page)
3. Do the specific form fields IDs for which we want placeholders exist? (they may not, depending on how the form was rendered)

Obviously, the possibilities here are endless. You have complete access to the entire DOM tree structure. You can write you own custom event handlers, dynamically change CSS styles/classes, new HTML objects/containers etc...

Please let me know if you have any other ideas.

Thanks -DE

**Comment by jayyx2** [comment]
Sounds amazing, thanks once again!
